# Generated by Django 3.2.2 on 2021-05-20 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('product_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('product_descrip', models.CharField(max_length=1000)),
                ('product_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta_contenido', models.CharField(max_length=5000)),
                ('product_lugarCompra', models.CharField(max_length=100)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.producto')),
            ],
        ),
    ]
