# Generated by Django 3.2.2 on 2021-05-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='product_calidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='product_calificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='product_precio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='product_precioTamano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='product_tiempoUso',
            field=models.IntegerField(default=0),
        ),
    ]
