# Generated by Django 3.2.2 on 2021-05-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210520_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='product_image',
            field=models.ImageField(default='Users\\diazm\\OneDrive\\Documents\\Django\\Laboratorio\\Laboratorio\\WebApp\\static\\images\\pic01.jpg', upload_to='post/%y/%m/%d'),
        ),
    ]
