# Generated by Django 3.2.2 on 2021-05-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210521_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='product_calidad',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (1, 'Muy Malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')], default=0),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='product_calificacion',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (1, 'Muy Malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')], default=0),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='product_precioTamano',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (1, 'Muy Malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')], default=0),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='product_tiempoUso',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (1, 'Muy Malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')], default=0),
        ),
    ]
