# Generated by Django 3.2.2 on 2021-05-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210521_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='product_calidad',
            field=models.CharField(choices=[(None, 'Seleccione'), ('MM', 'MUY MALO'), ('M', 'MALO'), ('R', 'REGULAR'), ('B', 'BUENO'), ('E', 'EXCELENTE')], default='R', max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='product_calificacion',
            field=models.CharField(choices=[(None, 'Seleccione'), ('MM', 'MUY MALO'), ('M', 'MALO'), ('R', 'REGULAR'), ('B', 'BUENO'), ('E', 'EXCELENTE')], default='R', max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='product_precioTamano',
            field=models.CharField(choices=[(None, 'Seleccione'), ('MM', 'MUY MALO'), ('M', 'MALO'), ('R', 'REGULAR'), ('B', 'BUENO'), ('E', 'EXCELENTE')], default='R', max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='product_tiempoUso',
            field=models.CharField(choices=[(None, 'Seleccione'), ('MM', 'MUY MALO'), ('M', 'MALO'), ('R', 'REGULAR'), ('B', 'BUENO'), ('E', 'EXCELENTE')], default='R', max_length=100),
        ),
    ]
