# Generated by Django 3.2.2 on 2021-05-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210521_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='product_calidad',
            field=models.CharField(choices=[(None, 'Seleccione'), ('Muy Malo', 'MUY MALO'), ('Malo', 'MALO'), ('Regular', 'REGULAR'), ('Bueno', 'BUENO'), ('Excelente', 'EXCELENTE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='product_calificacion',
            field=models.CharField(choices=[(None, 'Seleccione'), ('Muy Malo', 'MUY MALO'), ('Malo', 'MALO'), ('Regular', 'REGULAR'), ('Bueno', 'BUENO'), ('Excelente', 'EXCELENTE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='product_precioTamano',
            field=models.CharField(choices=[(None, 'Seleccione'), ('Muy Malo', 'MUY MALO'), ('Malo', 'MALO'), ('Regular', 'REGULAR'), ('Bueno', 'BUENO'), ('Excelente', 'EXCELENTE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='product_tiempoUso',
            field=models.CharField(choices=[(None, 'Seleccione'), ('Muy Malo', 'MUY MALO'), ('Malo', 'MALO'), ('Regular', 'REGULAR'), ('Bueno', 'BUENO'), ('Excelente', 'EXCELENTE')], max_length=100),
        ),
    ]
