# Generated by Django 3.2.2 on 2021-05-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210521_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejempo',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
