# Generated by Django 3.2.2 on 2021-05-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_ejempo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ejempo',
        ),
    ]
