# Generated by Django 3.2.2 on 2021-05-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_delete_ejempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='product_tiempoUso',
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='product_precioTamano',
            field=models.CharField(choices=[(None, 'Seleccione'), ('Muy barato', 'MUY BARATO'), ('Economico', 'ECONOMICO'), ('Aceptable', 'ACEPTABLE'), ('Costoso', 'COSTOSO'), ('Muy caro', 'MUY CARO')], max_length=100),
        ),
    ]
