# Generated by Django 3.2.2 on 2021-05-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210523_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='encuesta_contenido',
            field=models.TextField(max_length=5000),
        ),
    ]
