# Generated by Django 3.2.2 on 2021-05-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_encuesta_encuesta_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='encuesta_contenido',
            field=models.TextField(),
        ),
    ]
