# Generated by Django 3.2.2 on 2021-05-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_encuesta_encuesta_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='product_name',
            field=models.CharField(max_length=5000),
        ),
    ]
