# Generated by Django 3.2.2 on 2021-05-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_encuesta_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_name',
            field=models.CharField(max_length=200, primary_key=False),
        ),
    ]
