# Generated by Django 3.2.2 on 2021-05-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_encuesta_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='product_name',
            field=models.CharField(max_length=1000),
        ),
    ]
