# Generated by Django 3.2.2 on 2021-05-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_encuesta_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
