# Generated by Django 3.2.2 on 2021-05-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20210524_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
