# Generated by Django 3.2.2 on 2021-05-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_producto_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='serial',
            field=models.IntegerField(null=True),
        ),
    ]
