# Generated by Django 3.2.2 on 2021-05-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_producto_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='serial',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
