# Generated by Django 3.2.2 on 2021-05-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_producto_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='serial',
            field=models.IntegerField(null=True),
        ),
    ]
