# Generated by Django 3.2.2 on 2021-05-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_alter_producto_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
